services:
  web:
    image: odoo:17.0
    command: --config=/etc/odoo/odoo.conf  # ✅ Usar archivo de configuración
    depends_on:
      - db
    restart: always
    ports:
      - "9069:8069"  # Odoo web
      - "9072:8072"  # Odoo live chat (longpolling)
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo                    # ✅ Ruta donde está tu odoo.conf
      - ./addons:/mnt/extra-addons
      - odoo-log-data:/var/log/odoo           # ✅ Logs persistentes
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    secrets:
      - postgresql_password

volumes:
  odoo-web-data:
  odoo-db-data:
  odoo-log-data:  # ✅ volumen para logs

secrets:
  postgresql_password:
    file: odoo_pass
